import { Metadata } from 'next'

import './globals.css'

export const metadata: Metadata = {
  //   title: 'Next.js',
  //   description: 'Generated by Next.js',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="bg-mc text-mc-50 flex justify-center">
        <div className="w-full max-w-2xl px-2">{children}</div>
      </body>
    </html>
  )
}
